// 主题定义：每套主题由一组 CSS 变量驱动。
// Element 组件读 --el-color-*；侧边栏/品牌读 --app-*。
// 配色方案来自 ui-ux-pro-max 161 色库（玫红×蓝、活力橙×蓝等）及自定义衍生。

export const themes = [
  {
    id: 'rose',
    name: '玫红星河',
    desc: '玫瑰红 × 科技蓝，热烈抢眼',
    preview: ['#E11D48', '#FB7185', '#2563EB', '#FFF1F2'],
    vars: {
      '--el-color-primary': '#E11D48',
      '--el-color-primary-light-3': '#ea617f',
      '--el-color-primary-light-5': '#f08ea4',
      '--el-color-primary-light-7': '#f6bbc8',
      '--el-color-primary-light-8': '#f9d2da',
      '--el-color-primary-light-9': '#fce8ed',
      '--el-color-primary-dark-2': '#b4173a',
      '--el-color-success': '#10b981',
      '--el-color-warning': '#f59e0b',
      '--el-color-danger': '#ef4444',
      '--app-sb-bg': 'linear-gradient(180deg, #ffffff 0%, #fdf1f3 100%)',
      '--app-sb-text': '#4b4b61',
      '--app-sb-hover-bg': '#fdeef1',
      '--app-sb-hover-text': '#E11D48',
      '--app-sb-active-bg': 'linear-gradient(90deg, #fce8ed 0%, #fdeef1 100%)',
      '--app-sb-active-text': '#E11D48',
      '--app-sb-bar': 'linear-gradient(180deg, #E11D48, #FB7185)',
      '--app-accent': '#E11D48',
      '--app-accent2': '#2563EB',
      '--app-logo-from': '#E11D48',
      '--app-logo-to': '#FB7185',
      '--app-btn-gradient': 'linear-gradient(135deg, #E11D48 0%, #FB7185 100%)',
      '--app-btn-shadow': 'rgba(225, 29, 72, 0.45)'
    }
  },
  {
    id: 'orange',
    name: '活力橙',
    desc: '活力橙 × 信任蓝，温暖有冲劲',
    preview: ['#F97316', '#FB923C', '#2563EB', '#FFF7ED'],
    vars: {
      '--el-color-primary': '#F97316',
      '--el-color-primary-light-3': '#fb9d5c',
      '--el-color-primary-light-5': '#fcb98b',
      '--el-color-primary-light-7': '#fdd5b9',
      '--el-color-primary-light-8': '#fee3d0',
      '--el-color-primary-light-9': '#fef1e8',
      '--el-color-primary-dark-2': '#c75c12',
      '--el-color-success': '#10b981',
      '--el-color-warning': '#f59e0b',
      '--el-color-danger': '#ef4444',
      '--app-sb-bg': 'linear-gradient(180deg, #ffffff 0%, #fff4ec 100%)',
      '--app-sb-text': '#4b4b61',
      '--app-sb-hover-bg': '#fef0e2',
      '--app-sb-hover-text': '#F97316',
      '--app-sb-active-bg': 'linear-gradient(90deg, #fef1e8 0%, #fef0e2 100%)',
      '--app-sb-active-text': '#F97316',
      '--app-sb-bar': 'linear-gradient(180deg, #F97316, #FB923C)',
      '--app-accent': '#F97316',
      '--app-accent2': '#2563EB',
      '--app-logo-from': '#F97316',
      '--app-logo-to': '#FB923C',
      '--app-btn-gradient': 'linear-gradient(135deg, #F97316 0%, #FB923C 100%)',
      '--app-btn-shadow': 'rgba(249, 115, 22, 0.45)'
    }
  },
  {
    id: 'indigo',
    name: '靛紫蓝',
    desc: '靛紫蓝 × 品红，现代专业',
    preview: ['#5B5FEF', '#8B5CF6', '#EC4899', '#EFEFFD'],
    vars: {
      '--el-color-primary': '#5B5FEF',
      '--el-color-primary-light-3': '#8c8ff4',
      '--el-color-primary-light-5': '#adaff7',
      '--el-color-primary-light-7': '#cecffa',
      '--el-color-primary-light-8': '#dedffc',
      '--el-color-primary-light-9': '#efeffd',
      '--el-color-primary-dark-2': '#494cbf',
      '--el-color-success': '#10b981',
      '--el-color-warning': '#f59e0b',
      '--el-color-danger': '#ef4444',
      '--app-sb-bg': 'linear-gradient(180deg, #ffffff 0%, #f6f5ff 100%)',
      '--app-sb-text': '#4b4b61',
      '--app-sb-hover-bg': '#f3f1ff',
      '--app-sb-hover-text': '#5B5FEF',
      '--app-sb-active-bg': 'linear-gradient(90deg, #efeffd 0%, #f3f1ff 100%)',
      '--app-sb-active-text': '#5B5FEF',
      '--app-sb-bar': 'linear-gradient(180deg, #5B5FEF, #8B5CF6)',
      '--app-accent': '#5B5FEF',
      '--app-accent2': '#EC4899',
      '--app-logo-from': '#5B5FEF',
      '--app-logo-to': '#EC4899',
      '--app-btn-gradient': 'linear-gradient(135deg, #5B5FEF 0%, #8B5CF6 100%)',
      '--app-btn-shadow': 'rgba(91, 95, 239, 0.45)'
    }
  },
  {
    id: 'cyan',
    name: '清透青',
    desc: '天青 × 薄荷绿，通透清爽科技感',
    preview: ['#0EA5E9', '#22D3EE', '#10B981', '#E7F6FD'],
    vars: {
      '--el-color-primary': '#0EA5E9',
      '--el-color-primary-light-3': '#56c0f0',
      '--el-color-primary-light-5': '#87d2f4',
      '--el-color-primary-light-7': '#b7e4f8',
      '--el-color-primary-light-8': '#cfedfb',
      '--el-color-primary-light-9': '#e7f6fd',
      '--el-color-primary-dark-2': '#0b84ba',
      '--el-color-success': '#10b981',
      '--el-color-warning': '#f59e0b',
      '--el-color-danger': '#ef4444',
      '--app-sb-bg': 'linear-gradient(180deg, #ffffff 0%, #ecf9ff 100%)',
      '--app-sb-text': '#3f4b5c',
      '--app-sb-hover-bg': '#e8f7ff',
      '--app-sb-hover-text': '#0EA5E9',
      '--app-sb-active-bg': 'linear-gradient(90deg, #e7f6fd 0%, #e8f7ff 100%)',
      '--app-sb-active-text': '#0EA5E9',
      '--app-sb-bar': 'linear-gradient(180deg, #0EA5E9, #22D3EE)',
      '--app-accent': '#0EA5E9',
      '--app-accent2': '#10B981',
      '--app-logo-from': '#0EA5E9',
      '--app-logo-to': '#22D3EE',
      '--app-btn-gradient': 'linear-gradient(135deg, #0EA5E9 0%, #22D3EE 100%)',
      '--app-btn-shadow': 'rgba(14, 165, 233, 0.45)'
    }
  },
  {
    id: 'violet',
    name: '神秘紫',
    desc: '紫罗兰 × 洋红，神秘高级',
    preview: ['#8B5CF6', '#A78BFA', '#EC4899', '#F3EFFE'],
    vars: {
      '--el-color-primary': '#8B5CF6',
      '--el-color-primary-light-3': '#ae8df9',
      '--el-color-primary-light-5': '#c5aefb',
      '--el-color-primary-light-7': '#dccefc',
      '--el-color-primary-light-8': '#e8defd',
      '--el-color-primary-light-9': '#f3effe',
      '--el-color-primary-dark-2': '#6f4ac5',
      '--el-color-success': '#10b981',
      '--el-color-warning': '#f59e0b',
      '--el-color-danger': '#ef4444',
      '--app-sb-bg': 'linear-gradient(180deg, #ffffff 0%, #f6f1ff 100%)',
      '--app-sb-text': '#4b4b61',
      '--app-sb-hover-bg': '#f1eafe',
      '--app-sb-hover-text': '#8B5CF6',
      '--app-sb-active-bg': 'linear-gradient(90deg, #f3effe 0%, #f1eafe 100%)',
      '--app-sb-active-text': '#8B5CF6',
      '--app-sb-bar': 'linear-gradient(180deg, #8B5CF6, #EC4899)',
      '--app-accent': '#8B5CF6',
      '--app-accent2': '#EC4899',
      '--app-logo-from': '#8B5CF6',
      '--app-logo-to': '#EC4899',
      '--app-btn-gradient': 'linear-gradient(135deg, #8B5CF6 0%, #EC4899 100%)',
      '--app-btn-shadow': 'rgba(139, 92, 246, 0.45)'
    }
  }
]

export const defaultThemeId = 'rose'
